version: '3'

services:

  # Data API and authentication/authorization
  crawl:
    image: node:8.1.0-alpine
    hostname: crawl
    depends_on:
      - chrome-headless
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CORS_ORIGIN=http://localhost:3001,http://localhost:3000
      - DATABASE_URL=postgres://postgres@db:5432/dev
      - DATABASE_DEBUG=false
      - REDIS_URL=redis://redis:6379/0
      - SESSION_SECRET=wZjwhFtzQsd7r87W6AZw45Sm
      - JWT_SECRET=cnq9875w435nwehqc311os
      - FACEBOOK_ID=1821424564802638
      - FACEBOOK_SECRET=2339bdf25f236a42fc3a18280bf455e8
      - GOOGLE_ID=xxxxx.apps.googleusercontent.com
      - GOOGLE_SECRET=xxxxx
      - TWITTER_KEY=xxxxx
      - TWITTER_SECRET=xxxxx
    expose:
      - "8080"
    ports:
      - "127.0.0.1:9229:9229" # V8 inspector (when NODE_DEBUG=true)
    volumes:
      - yarn:/root/.cache/yarn
      - ./:/usr/src/app
    user: node
    working_dir: /usr/src/app
    command: node tools/run.js

  # SQL and document data store
  db:
    image: postgres:9.6.3-alpine
    read_only: true
    ports:
      - "5432:5432"
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
      - ./config/postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh

  # Distributed in-memory cache
  redis:
    image: redis:3.2.9-alpine
    read_only: true
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    user: redis

  chrome-headless:
    image: yukinying/chrome-headless:latest
    read_only: true
    ports:
      - "9222:9222"
    shm_size:
      256m
volumes:
  db:
  redis:
  yarn:
